name: push-action
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run building
        run: dotnet build PowerCollections/PowerCollections.csproj
  test:
    runs-on: windows-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Run tests
        run: dotnet test PowerCollections.Tests/PowerCollections.Tests.csproj